# tasks file for web
- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Get infos on container
  community.docker.docker_container_info:
    name: "web-{{ env }}"
  register: docker_info

- name: Stop a container
  docker_container:
    name: "web-{{ env }}"
    state: stopped
  when: docker_info.exists

- name: remove the container
  docker_container:
    name: "web-{{ env }}"
    state: absent
  when: docker_info.exists

- name: Display all variables/facts known for a host
  debug:
    var: "hostvars['{{ env }}.api'].ansible_host"
  tags: debug_info

- name: Deploy web service
  docker_container:
    name: "web-{{ env }}"
    image: "{{ web[env].web_image }}:{{ web[env].web_tag}}"
    ports:
      - "{{ web[env].web_port }}:80"
    env:
      APP_API_URL: "http://{{ hostvars[(env + '.api')].ansible_host }}"
      APP_API_VERSION: "api/v1"
